# Generated by Django 2.2 on 2020-04-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('discount_percent', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('vegetables', 'vegetables'), ('fruits', 'fruits'), ('juice', 'juice'), ('dried', 'dried')], max_length=120, null=True)),
            ],
        ),
    ]
